FROM node:20-alpine AS builder

WORKDIR /app

ENV npm_config_registry=https://registry.npmmirror.com

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

RUN apk --no-cache add ca-certificates wget

COPY nginx.prod.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --retries=3   CMD wget -q --spider http://localhost:3000 || exit 1

CMD ["nginx", "-g", "daemon off;"]
